### ISSUE TITLE
AttributeError: 'Entity' object has no attribute 'rotate'

### ISSUE THREAD

**Issue by Lvicek07** [mandaw2014/Rally#10]
Here is what was printed in terminal:

package_folder: /home/lvicek07/.local/lib/python3.10/site-packages/ursina
asset_folder: .
OS: posix
screen resolution: (1920, 1080)

Hello from the Rally Server!

no audio found with name: /ringtones/clicking.ogg supported formats: .ogg, .wav
no audio found with name: /ringtones/subtle.ogg supported formats: .ogg, .wav
no audio found with name: /ringtones/uplifting.ogg supported formats: .ogg, .wav
Known pipe types:
  glxGraphicsPipe
(4 aux display modules not yet loaded.)
Xlib:  extension "XFree86-DGA" missing on display ":0".
:device(warning): /dev/input/event6 is not readable, some features will be unavailable.
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
read obj at: assets/cars/sports-car.obj
read obj at: assets/cars/sports-car.obj
read obj at: assets/cars/muscle-car.obj
read obj at: assets/cars/limousine.obj
read obj at: assets/cars/lorry.obj
read obj at: assets/cars/hatchback.obj
read obj at: assets/cars/rally-car.obj
read obj at: assets/sand_track/sand_track.obj
read obj at: assets/grass_track/grass_track.obj
read obj at: assets/snow_track/snow_track.obj
read obj at: assets/forest_track/forest_track.obj
read obj at: assets/savannah_track/savannah_track.obj
read obj at: assets/lake_track/lake_track.obj
read obj at: assets/particles/particles.obj
read obj at: assets/sand_track/sand_track_bounds.obj
read obj at: assets/grass_track/grass_track_bounds.obj
read obj at: assets/snow_track/snow_track_bounds.obj
read obj at: assets/forest_track/forest_track_bounds.obj
read obj at: assets/savannah_track/savannah_track_bounds.obj
read obj at: assets/lake_track/lake_track_bounds.obj
read obj at: assets/sand_track/rocks-sand.obj
read obj at: assets/sand_track/cacti-sand.obj
read obj at: assets/grass_track/trees-grass.obj
read obj at: assets/grass_track/thintrees-grass.obj
read obj at: assets/grass_track/rocks-grass.obj
read obj at: assets/grass_track/grass-grass_track.obj
read obj at: assets/snow_track/trees-snow.obj
read obj at: assets/snow_track/thintrees-snow.obj
read obj at: assets/snow_track/rocks-snow.obj
read obj at: assets/forest_track/trees-forest.obj
:ffmpeg(warning): Could not update timestamps for skipped samples.
:ffmpeg(warning): Could not update timestamps for discarded samples.
read obj at: assets/forest_track/thintrees-forest.obj
read obj at: assets/cars/garage/cosmetics/viking_helmet.obj
read obj at: assets/savannah_track/rocks-savannah.obj
read obj at: assets/savannah_track/trees-savannah.obj
read obj at: assets/lake_track/trees-lake.obj
read obj at: assets/cars/garage/cosmetics/duck.obj
read obj at: assets/lake_track/thintrees-lake.obj
read obj at: assets/cars/garage/cosmetics/banana.obj
read obj at: assets/cars/garage/cosmetics/surfinbird.obj
read obj at: assets/lake_track/rocks-lake.obj
read obj at: assets/lake_track/bigrocks-lake.obj
read obj at: assets/lake_track/grass-lake.obj
read obj at: assets/cars/garage/cosmetics/surfboard.obj
:collide(error): Invalid points in CollisionPolygon:
  4.52877 0.015562 5.32231
  4.52877 0.015562 -2.62766
  4.52877 0.015562 -3.25315
  normal 0 -3.8147e-06 0 with length 3.8147e-06
:collide(error): Invalid points in CollisionPolygon:
  -5.17012 1.36712 -3.25559
  -5.17012 1.36712 5.3219
  -5.17012 1.36712 -2.67761
  normal 0 0 0 with length 1.06624e-06
:collide(error): Invalid points in CollisionPolygon:
  -5.17012 1.36712 -3.25559
  -5.17012 1.36712 7.70795
  -5.17012 1.36712 5.86507
  normal 0 0 0 with length 9.53674e-07
:collide(error): Invalid points in CollisionPolygon:
  3.45144 1.36712 -3.16898
  3.45144 1.36712 4.66929
  3.45144 1.36712 5.86548
  normal 0 1.90735e-06 0 with length 1.90735e-06
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
False
False
False
False
False
False
:pnmimage:png(warning): iCCP: known incorrect sRGB profile
info: development mode: True
application successfully started
Traceback (most recent call last):
  File "/home/lvicek07/.local/lib/python3.10/site-packages/ursina/main.py", line 143, in _update
    entity.update()
  File "/home/lvicek07/Desktop/Rally/car.py", line 731, in update
    self.rotation_parent.rotate((0, self.rotation_y + 180, 0))
AttributeError: 'Entity' object has no attribute 'rotate'
:task(error): Exception occurred in PythonTask update
Traceback (most recent call last):
  File "/home/lvicek07/Desktop/Rally/main.py", line 200, in <module>
    app.run()
  File "/home/lvicek07/.local/lib/python3.10/site-packages/ursina/main.py", line 239, in run
    super().run()
  File "/home/lvicek07/.local/lib/python3.10/site-packages/direct/showbase/ShowBase.py", line 3330, in run
    self.taskMgr.run()
  File "/home/lvicek07/.local/lib/python3.10/site-packages/direct/task/Task.py", line 553, in run
    self.step()
  File "/home/lvicek07/.local/lib/python3.10/site-packages/direct/task/Task.py", line 504, in step
    self.mgr.poll()
  File "/home/lvicek07/.local/lib/python3.10/site-packages/ursina/main.py", line 143, in _update
    entity.update()
  File "/home/lvicek07/Desktop/Rally/car.py", line 731, in update
    self.rotation_parent.rotate((0, self.rotation_y + 180, 0))
AttributeError: 'Entity' object has no attribute 'rotate'

**Comment by Lvicek07** [comment]
I tried "git clone" and .zip from releases, nothing worked

**Comment by FeltMacaroon389** [comment]
I have the same issue.

**Comment by FeltMacaroon389** [comment]
A fix for me was:
`pip uninstall ursina`
`pip install ursina`

**Comment by roboserg** [comment]
same error

**Comment by roboserg** [comment]
pip install  ursina==5.2.0
fixes the issue
