### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by narke** [mandaw2014/Rally#6]
The game doesn't start, the issue seems to be that the 'rotate" attribute isn't part of an Entity.

System info: Debian 11.5 x86_64
Python 3.9.2

```
pip install -r requirements.txt
python main.py
```

```
info: development mode: True
application successfully started
Traceback (most recent call last):
  File "/home/narke/.local/share/virtualenvs/rally/lib/python3.9/site-packages/ursina/main.py", line 143, in _update
    entity.update()
  File "/tmp/Rally/car.py", line 731, in update
    self.rotation_parent.rotate((0, self.rotation_y + 180, 0))
AttributeError: 'Entity' object has no attribute 'rotate'
:task(error): Exception occurred in PythonTask update
Traceback (most recent call last):
  File "/tmp/Rally/main.py", line 200, in <module>
    app.run()
  File "/home/narke/.local/share/virtualenvs/rally/lib/python3.9/site-packages/ursina/main.py", line 239, in run
    super().run()
  File "/home/narke/.local/share/virtualenvs/rally/lib/python3.9/site-packages/direct/showbase/ShowBase.py", line 3330, in run
    self.taskMgr.run()
  File "/home/narke/.local/share/virtualenvs/rally/lib/python3.9/site-packages/direct/task/Task.py", line 553, in run
    self.step()
  File "/home/narke/.local/share/virtualenvs/rally/lib/python3.9/site-packages/direct/task/Task.py", line 504, in step
    self.mgr.poll()
  File "/home/narke/.local/share/virtualenvs/rally/lib/python3.9/site-packages/ursina/main.py", line 143, in _update
    entity.update()
  File "/tmp/Rally/car.py", line 731, in update
    self.rotation_parent.rotate((0, self.rotation_y + 180, 0))
AttributeError: 'Entity' object has no attribute 'rotate'
```

**Comment by mandaw2014** [comment]
The rotate function is only in the newer version of ursina, try
`pip uninstall ursina`
and then
`pip install ursina`

**Comment by narke** [comment]
Thank you!
