### ISSUE TITLE
Cannot start game，python: 3.11

### ISSUE THREAD

**Issue by 0xCAFEBOY** [mandaw2014/Rally#9]
Great project, I would like to ask what version of python you are using? I encountered the following problem, 
- ursina version is 5.2.0
- python: 3.11

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ursina/main.py", line 143, in _update
    entity.update()
  File "/Users/easonguo/Downloads/Rally-master/car.py", line 731, in update
    self.rotation_parent.rotate((0, self.rotation_y + 180, 0))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Entity' object has no attribute 'rotate'
:task(error): Exception occurred in PythonTask update
Traceback (most recent call last):
  File "/Users/easonguo/Downloads/Rally-master/main.py", line 200, in <module>
    app.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ursina/main.py", line 239, in run
    super().run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/showbase/ShowBase.py", line 3330, in run
    self.taskMgr.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/task/Task.py", line 553, in run
    self.step()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/task/Task.py", line 504, in step
    self.mgr.poll()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ursina/main.py", line 143, in _update
    entity.update()
  File "/Users/easonguo/Downloads/Rally-master/car.py", line 731, in update
    self.rotation_parent.rotate((0, self.rotation_y + 180, 0))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Entity' object has no attribute 'rotate'
:thread(error): Exception occurred within PythonThread PythonThread-0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/direct/stdpy/thread.py", line 107, in threadFunc
    function(*args, **kwargs)
  File "/Users/easonguo/Downloads/Rally-master/main.py", line 98, in load_assets
    load_texture(t)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ursina/texture_importer.py", line 40, in load_texture
    t = Texture(filename.resolve())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ursina/texture.py", line 24, in __init__
    self._texture = loader.loadTexture(Filename.fromOsSpecific(str(value)))
                    ^^^^^^
NameError: name 'loader' is not defined. Did you mean: 'Loader'?

**Comment by 0xCAFEBOY** [comment]
when using windows rather than macOS, no problem
